set_property SRC_FILE_INFO {cfile:/scratch/anubhav/Coyote/hw/constraints/u280/shell/synth/u280_shell_base.xdc rfile:../../../../../../hw/constraints/u280/shell/synth/u280_shell_base.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores inst_debug_bridge_dynamic/inst/xsdbm]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores inst_debug_bridge_dynamic/inst/xsdbm]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores inst_debug_bridge_dynamic/inst/xsdbm]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port inst_debug_bridge_dynamic/inst/xsdbm/clk [get_nets dclk]
