# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: local.xdc

# Block Designs: bd/design_ctrl/design_ctrl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl || ORIG_REF_NAME==design_ctrl} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_xbar_0/design_ctrl_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_xbar_0 || ORIG_REF_NAME==design_ctrl_xbar_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_axi_interconnect_0_0/design_ctrl_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_axi_interconnect_0_0 || ORIG_REF_NAME==design_ctrl_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_clk_wiz_0_0/design_ctrl_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_clk_wiz_0_0 || ORIG_REF_NAME==design_ctrl_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_proc_sys_reset_a_0/design_ctrl_proc_sys_reset_a_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_proc_sys_reset_a_0 || ORIG_REF_NAME==design_ctrl_proc_sys_reset_a_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_proc_sys_reset_n_0/design_ctrl_proc_sys_reset_n_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_proc_sys_reset_n_0 || ORIG_REF_NAME==design_ctrl_proc_sys_reset_n_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_proc_sys_reset_u_0/design_ctrl_proc_sys_reset_u_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_proc_sys_reset_u_0 || ORIG_REF_NAME==design_ctrl_proc_sys_reset_u_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_s00_regslice_0/design_ctrl_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_s00_regslice_0 || ORIG_REF_NAME==design_ctrl_s00_regslice_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_s00_data_fifo_0/design_ctrl_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_s00_data_fifo_0 || ORIG_REF_NAME==design_ctrl_s00_data_fifo_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_m00_regslice_0/design_ctrl_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_m00_regslice_0 || ORIG_REF_NAME==design_ctrl_m00_regslice_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_cc_0/design_ctrl_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_cc_0 || ORIG_REF_NAME==design_ctrl_auto_cc_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_ds_0/design_ctrl_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_ds_0 || ORIG_REF_NAME==design_ctrl_auto_ds_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_pc_0/design_ctrl_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_pc_0 || ORIG_REF_NAME==design_ctrl_auto_pc_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_rs_0/design_ctrl_auto_rs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_rs_0 || ORIG_REF_NAME==design_ctrl_auto_rs_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_m01_regslice_0/design_ctrl_m01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_m01_regslice_0 || ORIG_REF_NAME==design_ctrl_m01_regslice_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_cc_1/design_ctrl_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_cc_1 || ORIG_REF_NAME==design_ctrl_auto_cc_1} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_ds_1/design_ctrl_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_ds_1 || ORIG_REF_NAME==design_ctrl_auto_ds_1} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_pc_1/design_ctrl_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_pc_1 || ORIG_REF_NAME==design_ctrl_auto_pc_1} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_rs_1/design_ctrl_auto_rs_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_rs_1 || ORIG_REF_NAME==design_ctrl_auto_rs_1} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_m02_regslice_0/design_ctrl_m02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_m02_regslice_0 || ORIG_REF_NAME==design_ctrl_m02_regslice_0} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_cc_2/design_ctrl_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_cc_2 || ORIG_REF_NAME==design_ctrl_auto_cc_2} -quiet] -quiet

# IP: bd/design_ctrl/ip/design_ctrl_auto_ds_2/design_ctrl_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ctrl_auto_ds_2 || ORIG_REF_NAME==design_ctrl_auto_ds_2} -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/bd/design_ctrl/design_ctrl_ooc.xdc
