# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/debug_bridge_dynamic/debug_bridge_dynamic.xci
# IP: The module: 'debug_bridge_dynamic' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/bd_2f3d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d || ORIG_REF_NAME==bd_2f3d} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_0/bd_2f3d_xsdbm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_xsdbm_0 || ORIG_REF_NAME==bd_2f3d_xsdbm_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_1/bd_2f3d_lut_buffer_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_lut_buffer_0 || ORIG_REF_NAME==bd_2f3d_lut_buffer_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_2/bd_2f3d_bs_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_bs_switch_0 || ORIG_REF_NAME==bd_2f3d_bs_switch_0} -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/bd_2f3d_ooc.xdc

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/debug_bridge_dynamic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_bridge_dynamic'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/debug_bridge_dynamic/debug_bridge_dynamic.xci
# IP: The module: 'debug_bridge_dynamic' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/bd_2f3d.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d || ORIG_REF_NAME==bd_2f3d} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_0/bd_2f3d_xsdbm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_xsdbm_0 || ORIG_REF_NAME==bd_2f3d_xsdbm_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_1/bd_2f3d_lut_buffer_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_lut_buffer_0 || ORIG_REF_NAME==bd_2f3d_lut_buffer_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/ip/ip_2/bd_2f3d_bs_switch_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2f3d_bs_switch_0 || ORIG_REF_NAME==bd_2f3d_bs_switch_0} -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/bd_0/bd_2f3d_ooc.xdc

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/debug_bridge_dynamic/debug_bridge_dynamic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_bridge_dynamic'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
