# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/bd_4611_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/bd_4611_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4611_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
