set cfg(fdev)                   u280
set cfg(shl_path)               /scratch/anubhav/Coyote/examples_hw/build_hw_8/package.tcl
set cfg(sim_path)               0
set cfg(static_path)            /scratch/anubhav/Coyote/examples_hw/..//hw/checkpoints
set cfg(shell_path)             0
set cfg(fplan_path)             0
set cfg(aclk_p)                 4
set cfg(nclk_p)                 4
set cfg(uclk_p)                 4
set cfg(hclk_p)                 2.22222
set cfg(build_static)           0
set cfg(build_shell)            1
set cfg(build_app)              0
set cfg(load_apps)              1
set cfg(n_xchan)                3
set cfg(n_schan)                2
set cfg(n_chan)                 1
set cfg(en_cred_local)          1
set cfg(en_cred_remote)         1
set cfg(n_reg)                  1
set cfg(en_strm)                1
set cfg(en_mem)                 0
set cfg(ddr_size)               34
set cfg(ddr_frag)               1024
set cfg(hbm_size)               33
set cfg(hbm_split)              0
set cfg(n_mem_chan)             0
set cfg(n_ddr_chan)             0
set cfg(n_tcp_chan)             0
set cfg(en_dcard)               0
set cfg(en_hcard)               0
set cfg(en_card)                0
set cfg(en_pr)                  0
set cfg(n_config)               1
set cfg(n_outs)                 8
set cfg(en_avx)                 1
set cfg(en_wb)                  1
set cfg(en_rdma)                0
set cfg(en_tcp)                 0   
set cfg(en_net_0)               1
set cfg(en_net_1)               0
set cfg(en_net)                 0   
set cfg(qsfp)                   0
set cfg(pmtu)                   4096
set cfg(cores)                  8
set cfg(build_opt)              0
set cfg(stat_probe)             1044942
set cfg(shell_probe)            1044942
set cfg(en_aclk)                1
set cfg(en_nclk)                1
set cfg(en_uclk)                0
set cfg(aclk_f)                 250
set cfg(nclk_f)                 250
set cfg(uclk_f)                 250
set cfg(hclk_f)                 450
set cfg(pol_inv)                0
set cfg(ddr_0)                  0
set cfg(ddr_1)                  0
set cfg(ddr_2)                  0
set cfg(ddr_3)                  0 
set cfg(strm_chan)              0
set cfg(card_chan)              -1
set cfg(en_xch_0)               1
set cfg(en_xch_1)               0
set cfg(tlbs_s)                 10
set cfg(tlbs_a)                 4
set cfg(tlbl_s)                 9
set cfg(tlbl_a)                 2
set cfg(tlbl_bits)              21
set cfg(tlbs_bits)              12
set cfg(n_tlb_actv)             16
set cfg(en_nru)                 0
set cfg(vit_hls)                1
set cfg(en_stats)               1
set cfg(net_drop)               0
set cfg(nr_st_s0)               2
set cfg(nr_st_s1)               2
set cfg(nr_sh_s0)               3
set cfg(nr_sh_s1)               2
set cfg(nr_dh_s0)               3
set cfg(nr_dh_s1)               3
set cfg(nr_dh_s2)               3
set cfg(nr_dc_s0)               3
set cfg(nr_dc_s1)               3
set cfg(nr_dc_s2)               3
set cfg(nr_dn_s0)               3
set cfg(nr_dn_s1)               3
set cfg(nr_dn_s2)               3
set cfg(nr_n_s0)                6
set cfg(nr_n_s1)                4
set cfg(nr_n_s2)                5
set cfg(nr_cc)                  4
set cfg(nr_e_s0)                3
set cfg(nr_e_s1)                2
set cfg(nr_sd)                  3
set cfg(nr_dd)                  3
set cfg(nr_pr)                  4
set cfg(nr_nst)                 4
set cfg(nr_xst)                 4
set cfg(eos_time)               1000000
set cfg(n_wbs)                  2
set cfg(n_strm_axi)             1
set cfg(mult_strm_axi)          0
set cfg(n_card_axi)             1
set cfg(mult_card_axi)          0
set cfg(n_rdma_axi)             1
set cfg(mult_rdma_axi)          0
set cfg(n_tcp_axi)              1
set cfg(mult_tcp_axi)           0
set cfg(n_net_chan)             0
set cfg(mult_regions)           0
set cfg(en_user_reg)            0
set cfg(en_xterm)               1
