# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.runs/synth_1/design_user_wrapper_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {Vivado 12-2924}  -suppress 
set_msg_config  -id {IP_Flow 19-4832}  -suppress 
set_msg_config  -id {BD 41-927}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu280-fsvh2892-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.cache/wt [current_project]
set_property parent.project_path /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /scratch/anubhav/Coyote/examples_hw/build_hw_8/iprepo [current_project]
update_ip_catalog
set_property ip_output_repo /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/lynx_macros.svh
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/axi_macros.svh
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/vfpga_top.svh
}
set_property file_type "Verilog Header" [get_files /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/lynx_macros.svh]
set_property file_type "Verilog Header" [get_files /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/axi_macros.svh]
set_property file_type "Verilog Header" [get_files /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/vfpga_top.svh]
read_verilog -library xil_defaultlib -sv {
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/lynx_pkg.sv
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/axi_intf.sv
  /scratch/anubhav/Coyote/hw/hdl/user/axis_mux/axis_mux_user_rd.sv
  /scratch/anubhav/Coyote/hw/hdl/user/axis_mux/axis_mux_user_wr.sv
  /scratch/anubhav/Coyote/hw/hdl/common/regs/axis_reg.sv
  /scratch/anubhav/Coyote/hw/hdl/common/regs/axisr_reg.sv
  /scratch/anubhav/Coyote/hw/hdl/user/dest/dest_req_arb.sv
  /scratch/anubhav/Coyote/hw/hdl/user/dest/dest_req_mux.sv
  /scratch/anubhav/Coyote/hw/hdl/user/dest/dest_req_seq.sv
  /scratch/anubhav/Coyote/hw/hdl/common/queues/fifo.sv
  /scratch/anubhav/Coyote/hw/hdl/user/mux_init/host_req_mux.sv
  /scratch/anubhav/Coyote/hw/hdl/user/credits/local_credits_host_rd.sv
  /scratch/anubhav/Coyote/hw/hdl/user/credits/local_credits_host_wr.sv
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/ext/raw/lynx_intf.sv
  /scratch/anubhav/Coyote/hw/hdl/common/regs/meta_reg.sv
  /scratch/anubhav/Coyote/hw/hdl/common/queues/queue_meta.sv
  /scratch/anubhav/Coyote/hw/hdl/common/queues/queue_stream.sv
  /scratch/anubhav/Coyote/hw/hdl/user/req/req_arb_2_1.sv
  /scratch/anubhav/Coyote/hw/hdl/user/credits/req_credits_rd.sv
  /scratch/anubhav/Coyote/hw/hdl/user/credits/req_credits_wr.sv
  /scratch/anubhav/Coyote/hw/hdl/user/req/req_parser.sv
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/wrappers/user_logic_c0_0.sv
  /scratch/anubhav/Coyote/hw/hdl/user/mux_init/user_req_mux.sv
  /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/hdl/wrappers/user_wrapper_c0_0.sv
}
read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axisr_data_fifo_512/axisr_data_fifo_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axisr_data_fifo_512/axisr_data_fifo_512_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/dwidth_converter_512_32/dwidth_converter_512_32.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/dwidth_converter_512_32/dwidth_converter_512_32_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/dwidth_converter_32_512/dwidth_converter_32_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/dwidth_converter_32_512/dwidth_converter_32_512_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/debug_bridge_user/debug_bridge_user.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/bd_4611_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/bd_4611_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/debug_bridge_user_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_512/axis_register_slice_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_512/axis_register_slice_512_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_512/axis_register_slice_512_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axisr_register_slice_512/axisr_register_slice_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axisr_register_slice_512/axisr_register_slice_512_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axisr_register_slice_512/axisr_register_slice_512_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_8/axis_register_slice_meta_8.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_8/axis_register_slice_meta_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_8/axis_register_slice_meta_8_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_16/axis_register_slice_meta_16.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_16/axis_register_slice_meta_16_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_16/axis_register_slice_meta_16_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_56/axis_register_slice_meta_56.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_56/axis_register_slice_meta_56_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_56/axis_register_slice_meta_56_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_64/axis_register_slice_meta_64.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_64/axis_register_slice_meta_64_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_64/axis_register_slice_meta_64_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_72/axis_register_slice_meta_72.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_72/axis_register_slice_meta_72_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_72/axis_register_slice_meta_72_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_96/axis_register_slice_meta_96.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_96/axis_register_slice_meta_96_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_96/axis_register_slice_meta_96_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_128/axis_register_slice_meta_128.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_128/axis_register_slice_meta_128_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_128/axis_register_slice_meta_128_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_256/axis_register_slice_meta_256.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_256/axis_register_slice_meta_256_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_256/axis_register_slice_meta_256_ooc.xdc]

read_ip -quiet /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_register_slice_meta_512/axis_register_slice_meta_512.xci
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_512/axis_register_slice_meta_512_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_register_slice_meta_512/axis_register_slice_meta_512_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/xdc/user_clk_c0_0.xdc
set_property used_in_implementation false [get_files /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/xdc/user_clk_c0_0.xdc]

read_xdc /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/constrs_1/local.xdc
set_property used_in_implementation false [get_files /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/constrs_1/local.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_user_wrapper_0 -part xcu280-fsvh2892-2L-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_user_wrapper_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_user_wrapper_0_utilization_synth.rpt -pb design_user_wrapper_0_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
