# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/debug_bridge_user/debug_bridge_user.xci
# IP: The module: 'debug_bridge_user' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/bd_4611.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611 || ORIG_REF_NAME==bd_4611} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/bd_4611_xsdbm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611_xsdbm_0 || ORIG_REF_NAME==bd_4611_xsdbm_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_1/bd_4611_lut_buffer_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611_lut_buffer_0 || ORIG_REF_NAME==bd_4611_lut_buffer_0} -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/bd_4611_ooc.xdc

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/debug_bridge_user_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_bridge_user'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/debug_bridge_user/debug_bridge_user.xci
# IP: The module: 'debug_bridge_user' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/bd_4611.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611 || ORIG_REF_NAME==bd_4611} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_0/bd_4611_xsdbm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611_xsdbm_0 || ORIG_REF_NAME==bd_4611_xsdbm_0} -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/ip/ip_1/bd_4611_lut_buffer_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4611_lut_buffer_0 || ORIG_REF_NAME==bd_4611_lut_buffer_0} -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/bd_0/bd_4611_ooc.xdc

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/debug_bridge_user/debug_bridge_user_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_bridge_user'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
