# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512.xci
# IP: The module: 'axis_data_fifo_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.srcs/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512.xci
# IP: The module: 'axis_data_fifo_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/test.gen/sources_1/ip/axis_data_fifo_512/axis_data_fifo_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
