# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/dyn_crossbar_0/dyn_crossbar_0.xci
# IP: The module: 'dyn_crossbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/dyn_crossbar_0/dyn_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dyn_crossbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/dyn_crossbar_0/dyn_crossbar_0.xci
# IP: The module: 'dyn_crossbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/dyn_crossbar_0/dyn_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dyn_crossbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
