# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axim_register_slice/axim_register_slice.xci
# IP: The module: 'axim_register_slice' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axim_register_slice/axim_register_slice_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axim_register_slice'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axim_register_slice/axim_register_slice_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axim_register_slice'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axim_register_slice/axim_register_slice.xci
# IP: The module: 'axim_register_slice' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axim_register_slice/axim_register_slice_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axim_register_slice'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axim_register_slice/axim_register_slice_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axim_register_slice'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
