set_property SRC_FILE_INFO {cfile:/scratch/anubhav/Coyote/examples_hw/build_hw_8/test_config_0/user_c0_0/xdc/user_clk_c0_0.xdc rfile:../../../xdc/user_clk_c0_0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores inst_debug_bridge_user/inst/xsdbm]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores inst_debug_bridge_user/inst/xsdbm]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores inst_debug_bridge_user/inst/xsdbm]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port inst_debug_bridge_user/inst/xsdbm/clk   [get_nets dclk]
