# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axis_clock_converter_96/axis_clock_converter_96.xci
# IP: The module: 'axis_clock_converter_96' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_clock_converter_96/axis_clock_converter_96_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_clock_converter_96'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axis_clock_converter_96/axis_clock_converter_96.xci
# IP: The module: 'axis_clock_converter_96' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_clock_converter_96/axis_clock_converter_96_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_clock_converter_96'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
