# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32.xci
# IP: The module: 'axis_register_slice_meta_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_meta_32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_meta_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.srcs/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32.xci
# IP: The module: 'axis_register_slice_meta_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_meta_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /scratch/anubhav/Coyote/examples_hw/build_hw_8/test_shell/test.gen/sources_1/ip/axis_register_slice_meta_32/axis_register_slice_meta_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_meta_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
